---
AllCops:
  TargetRubyVersion: 2.4
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 200
Metrics/ModuleLength:
  Max: 250
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 50


# Shh
Security/Eval:
  Enabled: false
Security/YAMLLoad:
  Enabled: false