version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
      - image: redis:4.0.1
    steps:
      - checkout
      - run:
          name: Wait for Redis to start
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: gradle test
